name: "base"
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - plotly=4.14.3
  - hdfs3
  - pip
  - pip:
      - scikit-learn
      - geopandas
      - pyspark
# - add packages here
# - one per line
prefix: "/opt/conda"

